name = "protein2x7"
main = "src/index.ts"
compatibility_date = "2025-09-03"
account_id = "199e4dc100e5e7849f6e2bf98daa6dce"
workers_dev = true

# Worker configuration
[vars]
ENVIRONMENT = "production"
API_VERSION = "v1"
JWT_SECRET = "your-super-secret-jwt-key-change-in-production-2024"
R2_PUBLIC_URL = "https://cdn.protein2x7.shop"

# D1 Database configuration
[[d1_databases]]    
binding = "DB"
database_name = "protein2x7"    
database_id = "5790509d-5413-42f8-81be-ed792b4ad09d"    
preview_database_id = "5790509d-5413-42f8-81be-ed792b4ad09d"

# R2 bucket configuration
[[r2_buckets]]
binding = "bucket_name"   
bucket_name = "protein2x7"
preview_bucket_name = "protein2x7"

# Observability
[observability]
enabled = true
head_sampling_rate = 1